### ISSUE TITLE
usbreplay.py did not claim interface 0 before use

### ISSUE THREAD

**Issue by deelerke** [wcooley/usbrevue#3]
Hey!

I _sometimes_ get this error message in the dmesg

[532342.976406] usb 2-2: usbfs: process 27349 (usbreplay.py) did not claim interface 0 before use

This happens mostly when there was a long time before i executed a replay.
The second time I try it (right after), the replay works fine.

I know: still a bit vague on when exactly this is happening.... I should test more for exact numbers.

**Comment by wcooley** [comment]
Hm, [this](http://stackoverflow.com/a/13367026/627003) sounds like what might be happening:

> Apparently, if the driver is first detached, and then interface is claimed - then no errors are generated. But that is also what you have in OP there - so I think, the trick for OP would be to have detach, then set configuration, and after that claim interface...

What happens if you move the line:

```
   self.set_configuration(self.logical_cfg)
```

to below the following _if_ block, where it checks for and detaches the kernel driver?

```
--- a/usbreplay.py
+++ b/usbreplay.py
@@ -124,13 +124,14 @@ class Replayer(object):
             raise ValueError('The device with vid=0x%x, pid=0x%x is not connected') % (self.vid, self.pid)

         self.logical_cfg = logical_cfg
-        self.set_configuration(self.logical_cfg)
         self.logical_iface = logical_iface

         if self.device.is_kernel_driver_active(self.logical_iface):
             if self.debug: sys.stderr.write( 'Detaching kernal driver\n')
             self.device.detach_kernel_driver(self.logical_iface)

+        self.set_configuration(self.logical_cfg)
+
         self.logical_alt_setting = logical_alt_setting
         self.set_interface(self.logical_iface, self.logical_alt_setting)
```

**Comment by deelerke** [comment]
Hello ! 

it's okay to close this case, for some reason it's not happening anymore.... (I did an apt-get dist-upgrade and updated a lot of packages, so I'm not exactly sure what fixed it).

thank you
